### ISSUE TITLE
STEP : 'Start by making an experiment folder and preprocessing the data'  error

### ISSUE THREAD

**Issue by zozni** [MGheini/xattn-transfer-for-mt#2]
cp: 'De-En/iwslt15.tune.tok.de' Unexplained: No such file or directory
cp: 'De-En/iwslt15.tune.tok.en' Unexplained: No such file or directory
cp: 'De-En/iwslt13.test.tok.de' Unexplained: No such file or directory
cp: 'De-En/iwslt13.test.tok.en' Unexplained: No such file or directory
cp: 'De-En/iwslt16.train.tok.de' Unexplained: No such file or directory
cp: 'De-En/iwslt16.train.tok.en' Unexplained: No such file or directory
. . .
FileNotFoundError: [Errno 2] No such file or directory: 'test_exp//data/train.bpe.de'

How to solve this problem?

**Comment by MGheini** [comment]
Can you provide some more details? For instance, have you downloaded and prepared the data?

**Comment by zozni** [comment]
Oh I set the path wrong. Sorry. Thank you for answer!!!
